# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440\u043a\u0430'),
        ),
    ]
