# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160528_2339'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.img', null=True, upload_to='avatars', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
