# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='service',
            name='avatar',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='users',
            field=models.ManyToManyField(blank=None, to=settings.AUTH_USER_MODEL, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u044b'),
        ),
    ]
