# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20160528_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u044b'),
        ),
    ]
