# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20160604_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=datetime.datetime(2016, 6, 4, 21, 20, 31, 672333, tzinfo=utc), verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
