# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', null=True, upload_to='avatars', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
