# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20160605_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='works.Employee', verbose_name='\u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
